
KEYS = [
    "file_id", "ref_id",
]

PRE2_COLS_FINAL = [
    "file_id", "ref_id",
    "acquirer_bin",
    "app_date_valid",
    "business_mode",
    "card_program_identifier",
    "card_purchase_country",
    "card_purchase_region",
    "funding_source",
    "gcms_product_identifier",
    "high_key_for_range",
    "iar_country",
    "iss_bin_6",
    "iss_bin_8",
    "jurisdiction",
    "jurisdiction_country",
    "jurisdiction_region",
    "low_key_for_range",
    "num_card_high",
    "num_card_low",
    "purchase_date",
    "settlement_indicator",
]

EXRATE_COLS_FINAL = [
    "file_id", "ref_id",
    "amount_reconciliation",
    "amount_transaction",
    "currency_code_reconciliation",
    "currency_code_transaction",
    "exchange_value_local",
    "exchange_value_settlement",
    "local_currency_code",
    "local_currency_code_numeric",
    "settlement_currency_code",
    "settlement_currency_code_numeric",
]

AMOUNT_COLS_FINAL = [
    "file_id", "ref_id",
    "settlement_report_amount",
    "settlement_report_currency_code",
]

CALCULATE_FIELDS_FINAL = {
    "file_id": "string",
    "ref_id": "int64",
    "acquirer_bin": "int64",
    "app_date_valid": "",
    "business_mode": "string",
    "card_program_identifier": "string",
    "card_purchase_country": "string",
    "card_purchase_region": "int64",
    "funding_source": "string",
    "gcms_product_identifier": "string",
    "iar_country": "string",
    "iss_bin_6": "int64",
    "iss_bin_8": "int64",
    "low_key_for_range": "int64",
    "high_key_for_range": "int64",
    "num_card_low": "int64",
    "num_card_high": "int64",
    "jurisdiction": "string",
    "jurisdiction_country": "string",
    "jurisdiction_region": "int64",
    "purchase_date": "timestamp",
    "settlement_indicator": "string",
    "local_currency_code": "string",
    "local_currency_code_numeric": "int64",
    "settlement_currency_code": "string",
    "settlement_currency_code_numeric": "int64",
    "exchange_value_local": "decimal",
    "exchange_value_settlement": "decimal",
    "currency_code_reconciliation": "int64",
    "amount_reconciliation": "decimal",
    "currency_code_transaction": "int64",
    "amount_transaction": "decimal",
    "settlement_report_amount": "decimal",
    "settlement_report_currency_code": "string",
}

# CALCULATE_FIELDS_FINAL = {
#     "file_id": "string",
#     "ref_id": "int64",
#     "acquirer_bin": "int64",
#     "app_date_valid": "date",
#     "business_mode": "string",
#     "card_program_identifier": "string",
#     "card_purchase_country": "string",
#     "card_purchase_region": "int64",
#     "funding_source": "string",
#     "gcms_product_identifier": "string",
#     "iar_country": "string",
#     "iss_bin_6": "int64",
#     "iss_bin_8": "int64",
#     "low_key_for_range": "int64",
#     "high_key_for_range": "int64",
#     "num_card_low": "int64",
#     "num_card_high": "int64",
#     "jurisdiction": "string",
#     "jurisdiction_assigned": "string",
#     "jurisdiction_country": "string",
#     "jurisdiction_region": "int64",
#     "purchase_date": "timestamp",
#     "settlement_indicator": "string",
#     "local_currency_code": "string",
#     "local_currency_code_numeric": "int64",
#     "settlement_currency_code": "string",
#     "settlement_currency_code_numeric": "int64",
#     "exchange_value_local": {"dtype": "decimal", "precision": 18, "scale": 4},
#     "exchange_value_settlement": {"dtype": "decimal", "precision": 18, "scale": 4},
#     "currency_code_reconciliation": "int64",
#     "amount_reconciliation": {"dtype": "decimal", "precision": 18, "scale": 4},
#     "currency_code_transaction": "int64",
#     "amount_transaction": {"dtype": "decimal", "precision": 18, "scale": 4},
#     "settlement_report_amount": {"dtype": "decimal", "precision": 18, "scale": 4},
#     "settlement_report_currency_code": "string",
# }


CALCULATE_FIELDS_FINAL = {
    "file_id": "string",
    "ref_id": "int64",
    "file_idn": "String",
    "file_type": "String",
    "client_id": "String",
    "file_dt": "Int64",
    "type_mti": "Int64",
    "business_mode": "string",
    "jurisdiction": "string",
    "jurisdiction_country": "string",
    "jurisdiction_region": "int64",
    "funding_source": "string",
    "gcms_product_identifier": "string",
    "card_program_identifier": "string",
    "jurisdiction_assigned": "string",
    "settlement_report_currency_code": "string",
    "settlement_report_amount": {"dtype": "decimal", "precision": 18, "scale": 4},
    "iar_country": "string",
    "exclude_flag" : "int64",
}
